/**
 * ============================================================
 * KEF Global Membership Information System (KGMIS)
 * Global Configuration
 * File Name: 00_kgmis_config.gs
 * Designed & Developed by JJA Global Systems
 * ============================================================
 */

const KGMIS_CONFIG = Object.freeze({

  MASTER_SHEET: "KGMIS_MASTER_DATABASE_v1.0",
  SYSTEM_SHEET: "KGMIS_SYSTEM",
  ACCESS_CONTROL_SHEET: "KGMIS_ACCESS_CONTROL",

  FAMILY_MEMBERS_SHEET: "KEFG_FAMILY_MEMBERS",
  FAMILY_MEMBER_UPDATE_REQUESTS_SHEET: "KGMIS_FAMILY_MEMBER_UPDATE_REQUESTS",

  FINANCIAL_YEAR_SHEET: "KGMIS_FINANCIAL_YEAR",
  MEMBERSHIP_YEAR_SHEET: "KGMIS_MEMBERSHIP_YEAR",
  RECEIPT_TRANSACTIONS_SHEET: "KGMIS_RECEIPT_TRANSACTIONS",
  PAYMENT_TRANSACTIONS_SHEET: "KGMIS_PAYMENT_TRANSACTIONS",

  PAYMENT_VOUCHER_FOLDER_ID: "13es9ds8yPDxc3oPngSKoqVPtpFIyyGB_",
  PAYMENT_LOGO_FILE_ID: "1hna_OXAqjBi_W0u9F8tGWO564y4IJTvj",

  RECEIPT_FOLDER_ID: "15R3nhfT1xnKpi2vBMKiYJDYywtQv6p0t",
  RECEIPT_LOGO_FILE_ID: "1hna_OXAqjBi_W0u9F8tGWO564y4IJTvj",

  AUDIT_LOG_SHEET: "KGMIS_AUDIT_LOG",
  CONFIGURATION_SHEET: "KGMIS_CONFIGURATION",

  DIGITAL_CARD_FOLDER_ID: "1eL2kxRk97vFsMqKi3508w8fhQi-TSlCi",
  DIGITAL_CARD_PHOTOS_FOLDER_ID: '1QH6L-ewvk48Ycx3SS50dmQuSghwmPwkB',

  HEADER_ROW: 1,
  FIRST_DATA_ROW: 2,

  ID_HEADER: "KEFG_ID",
  NAME_HEADER: "MEMBER_NAME",
  ID_PREFIX: "KEFG",
  ID_START_NUMBER: 1001,
  ID_DIGITS: 4,

  SOURCE_TYPE: Object.freeze({
    MEMBER: "MEMBER",
    DEPENDANT: "DEPENDANT"
  }),

  CARD_SHEET: "KEFG_MEMBER_CARDS",
  CARD_VERSION: "1.0",

  CARD_STATUS: Object.freeze({
    ACTIVE: "ACTIVE",
    EXPIRED: "EXPIRED",
    SUSPENDED: "SUSPENDED",
    REVOKED: "REVOKED",
    CANCELLED: "CANCELLED"
  }),

  CARD_STATE: Object.freeze({
    GENERATED: "GENERATED",
    PDF_CREATED: "PDF_CREATED",
    IMAGE_CREATED: "IMAGE_CREATED",
    PUBLISHED: "PUBLISHED",
    VERIFIED: "VERIFIED"
  }),

  CARDHOLDER_TYPE: Object.freeze({
    PRIMARY_MEMBER: "PRIMARY MEMBER",
    SPOUSE: "SPOUSE",
    CHILD: "CHILD",
    PARENT: "PARENT",
    IN_LAW: "IN-LAW"
  })

});
